console.log("Paso 1: Colocar 2 huevos, 1 Taza de azucar y la esencia de vainilla en un recipiente y batir hasta hacer la mezcla homogenea (aprox 1 min");
console.log("Paso 2: Añadir 1/2 taza de aqceite y mezclar.");
console.log("Paso 3: Luego agregar una taza de harina y volver a mezclar.");
console.log("Paso 4: Agregar 3/4 taza de leche y mezclar nuevamente.");
console.log("Paso 5: Por último agregar la taza de harina restante y mezclar todo por aproximadamente 1 minuto.");
console.log("Paso 6: Volcar la mezcla en un molde apropiado y llevar al horno a 150º.");
console.log("Paso 7: Luego de 45 min. retirarl del horno y dejar reposar para que se enfrie.");
console.log("Paso 8: Desmoldar.");
console.log("Paso 9: Esporvorear con azucar impalpable para decorar.");
console.log("Paso 10: SERVIR.");
