console.log("1. Salir por calle Velez Sarfield hacia avenida Urquiza.");
console.log("2. Doblar a la derecha.");
console.log("3. Tomar Av. Urquiza hasta llegar a la rotonda de Av. Trabajadores.");
console.log("4. En la rotonda girar hacia la izquierda.");
console.log("5. Tomar Av. Trabajadores hasta llegar al paso nivel de calle Amparo Castro.");
console.log("6. ¡CUIDADO EL PASO NIVEL!, si no se aproxima el tren por ninguno de los extremos, cruzar las vias.");
console.log("7. Seguir derecho hasta llegar a calle Moreno.");
console.log("8. Doblar a la derecha.");
console.log("9. Avanzar por calle Moreno hasta topar con el predio del supermercado.");
console.log("10. Girar a la izquierda.");
console.log("11. Puede verse el arco de entrada, avanzar unos metros hasta poder ingresar al predio.");
console.log("12. Busque estacionamiento y ¡A INVERTIR SU DINERO!");
