console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Girar a la izquierda 90º");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");
console.log("Avanzar");
console.log("Quitar 1");